# Generated by Django 4.0.2 on 2022-02-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_filier_room_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='Filier',
            field=models.ManyToManyField(blank=True, to='base.Filier'),
        ),
    ]
