# Generated by Django 4.0.2 on 2022-02-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_topic_filier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
